apiVersion: apps/v1
kind: Deployment
metadata:
 name: kubei
 labels:
  app: kubei
spec:
 replicas: 1
 selector:
  matchLabels:
   app: kubei
 template:
  metadata:
   labels:
    app: kubei
  spec:
   containers:
    - image: kings.azurecr.io/king:420
      name: kubei
      ports:
       - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: kubei
  labels:
    app: kubei
spec:
  type: NodePort
  selector:
    app: kubei
  ports:
  - protocol: TCP
    port: 3000       # Service's port
    targetPort: 3000 # Container's port
    nodePort: 30007